# Generated by Django 2.1.7 on 2020-03-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_sportnews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Novidades',
        ),
    ]
