# Generated by Django 2.1.7 on 2020-03-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20200312_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Novidades',
            new_name='Novidade',
        ),
    ]
